### ISSUE TITLE
ubuntu python3.4编码错误

### ISSUE THREAD

**Issue by SakagamiJun** [losisli/dmzjComic#1]
root@Misaka:~/dmzjComic# python3.4 dmzjComic.py -u http://manhua.dmzj.com/alsymlsyj/
Traceback (most recent call last):
  File "dmzjComic.py", line 227, in <module>
    main(url, path, lst)
  File "dmzjComic.py", line 141, in main
    print('\u6f2b\u753b\u540d: {}'.format(comicName))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)

**Comment by losisli** [comment]
不好意思,手头没有linux环境,无法重现问题.看你的错误输出没能正确显示中文,是不是你的环境变量系统编码不支持中文呢,用 ``locale``命令查看一下.
